workflow:
  rules:
  - if: $CI_COMMIT_MESSAGE =~ /.*(\[Release\]|quick-build).*/
    when: never
  - if: $CI_COMMIT_AUTHOR =~ /ci-spireon.*/
    when: never
  - if: $CI_PIPELINE_SOURCE == "external_pull_request_event"
  - if: $CI_COMMIT_BRANCH =~ /(citest*|master|main|dev.*|PR.*|release.*|test)/

cache:
  key: $CI_COMMIT_BRANCH
  paths:
  - .m2/repository
  - .sonar/cache
  
include:
- project: spireon/devops/cicd/include-files
  file: default/grails.gitlab-ci.yml
- project: spireon/devops/cicd/include-files
  file: default/sonarqube.gitlab-ci.yml

default:
  image: registry.gitlab.com/spireon/devops/cicd/docker/java8builder:master

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PUBLISH_TO_DOCKERHUB: "false"
  PUBLISH_TO_GITLAB_CONTAINER_REGISTRY: "false"
  PUBLISH_TO_GITLAB_PACKAGE_REGISTRY: "false"
  SEMVER_MAIN_BUMP_TYPE: "patch"
