workflow:
  rules:
  - if: $CI_COMMIT_MESSAGE =~ /.*(\[Release\]|quick-build).*/
    when: never
  - if: $CI_COMMIT_AUTHOR =~ /ci-spireon.*/
    when: never
  - if: $CI_PIPELINE_SOURCE == "external_pull_request_event"
  - if: $CI_PIPELINE_SOURCE == "web"
  - if: $CI_COMMIT_BRANCH =~ /(ci-test|master|main|dev.*|PR.*|release.*|test)/
  
include:
- project: spireon/devops/cicd/include-files
  file: default/grails.gitlab-ci.yml
- project: spireon/devops/cicd/include-files
  file: default/sonarqube.gitlab-ci.yml

default:
  image: registry.gitlab.com/spireon/devops/cicd/docker/java8builder:master

variables:
  PUBLISH_TO_NEXUS: "false"

